...
defaults:
  - scope:
      path: ''
      type: 'posts' 
    values:
      layout: 'posts'
  - scope:
      path: ''
      type: 'pages' 
    values:
      author: 'Pieter-Jan'
...

title: Working title
theme: minima
